version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: ./docker/nginx/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - '9000:80'
        links:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php7.docker
        volumes:
            - ./:/var/www

    db:
        image: mysql:5.7
        env_file: .env
        volumes:
            # add database dump in the folder, docker will dump it into the db
            - ./docker/sql-dump:/docker-entrypoint-initdb.d
            # keep database binary outside container
            - ./docker/sql-binary:/var/lib/mysql
        ports:
            - '33061:3306'

networks:
    default:
        external:
            name: nginx_proxy
