version: '3'
services:

  web-nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/DockerFile
    volumes:
      - ./:/var/www
    environment:
      - VIRTUAL_HOST=ldocker-kit-nginx.com
    links:
      - php

  web-apache:
    build:
      context: ./
      dockerfile: ./docker/apache2/DockerFile
    volumes:
      - ./:/var/www
    environment:
      - VIRTUAL_HOST=ldocker-kit-apache.com
    links:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/7.2/Dockerfile
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  default:
    external:
      name: global_network