version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: development/docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: development/docker/php7.docker
        volumes:
            - ./:/var/www

    database:
        image: mysql:5.7
        environment:
            - "MYSQL_DATABASE=myapp"
            - "MYSQL_USER=myapp"
            - "MYSQL_PASSWORD=password"
            - "MYSQL_ROOT_PASSWORD=password"
        ports:
            - "33061:3306"

    phpmyadmin:
        image:  phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - database:db